server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5433/postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:db/initDB.sql
      data-locations: classpath:db/populateDB.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: datajpa, jdbc
  security:
    user:
      name: user
      password: pass2

